apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-server-cm
  namespace: insanityid
data:
  APP_BASE_URL: http://id.insanity.local

  DDL_AUTO: validate
  DB_HOST: host.minikube.internal
  DB_PORT: "5432"
  DB_SCHEMA_NAME: cams_auth

  REDIS_HOST: host.minikube.internal
  REDIS_PORT: "6379"

  SESSION_TIMEOUT_DURATION: "6h"

  SMTP_PORT: "587"
  SMTP_USE_AUTH: "true"
  SMTP_STARTTLS_ENABLE: "true"
  SMTP_STARTTLS_REQUIRED: "true"

  LOG_LEVEL: DEBUG
  LOG_REQUEST_DETAILS: "true"

  AUTH_SERVER_ISSUER_URI: http://id.insanity.local
  AUTH_KEY_PUBLIC_PATH: /etc/ssl/certs/public.pem
  AUTH_KEY_PRIVATE_PATH: /etc/ssl/certs/private.pem
  AUTH_KEY_ID: faac112a-1060-4bd7-9582-a4590390ee67
